name: Integration Tests
on:
  push:
    branches:
      - master
      - test-action-new-cli
  pull_request:
jobs:
  integration-tests:
    env:
      TEST_ROOT: ${{github.workspace}}/Laboratory/Integration
      RUNTIME_ROOT: ${{github.workspace}}/Runtime/C#
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.0.x
            6.0.x
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Setup C++
        run: |
          sudo apt update
          sudo apt install gcc g++ zsh
      - name: Build TS Runtime
        run: |
          npm install
          npm run build
        working-directory: ./Runtime/TypeScript
      - name: Test
        run: zsh run_test.sh
        working-directory: ${{env.TEST_ROOT}}
